repos:
  # golang pre commits
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: no-go-testing
      - id: golangci-lint
        args: ["--skip-dirs=vendor -c .golang-ci.yml ."]
      - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy

  # gitlab ci lint
  - repo: https://github.com/FalcoSuessgott/lint-gitlab-ci
    rev: v0.0.4
    hooks:
      - id: gitlab-ci
#
#
##!/bin/bash
##
## An example hook script to verify what is about to be committed.
## Called by "git commit" with no arguments.  The hook should
## exit with non-zero status after issuing an appropriate message if
## it wants to stop the commit.
##
## To enable this hook, rename this file to "pre-commit".
#  set -e
#
#  make lint || (echo "lint failed"; exit 1)
#
#  if git rev-parse --verify HEAD >/dev/null 2>&1
#  then
#  against=HEAD
#  else
#  # Initial commit: diff against an empty tree object
#  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
#  fi
#
#
#  # If there are whitespace errors, print the offending file names and fail.
#  exec git diff-index --check --cached $against --
